export const REQUEST_API_REPOSITORIES = 'REQUEST_API_REPOSITORIES'
export const RECEIVE_API_REPOSITORIES = 'RECEIVE_API_REPOSITORIES'

export const REQUEST_API_USERS = 'REQUEST_API_USERS'
export const RECEIVE_API_USERS = 'RECEIVE_API_USERS'

export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'